//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UgvAssignment
{
    [Serializable]
    public class InputMsg : Message
    {
        public const string k_RosMessageName = "ugv_assignment_msgs/Input";
        public override string RosMessageName => k_RosMessageName;

        public double throttle;
        public double brake;
        public double steering_angle;

        public InputMsg()
        {
            this.throttle = 0.0;
            this.brake = 0.0;
            this.steering_angle = 0.0;
        }

        public InputMsg(double throttle, double brake, double steering_angle)
        {
            this.throttle = throttle;
            this.brake = brake;
            this.steering_angle = steering_angle;
        }

        public static InputMsg Deserialize(MessageDeserializer deserializer) => new InputMsg(deserializer);

        private InputMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.throttle);
            deserializer.Read(out this.brake);
            deserializer.Read(out this.steering_angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.throttle);
            serializer.Write(this.brake);
            serializer.Write(this.steering_angle);
        }

        public override string ToString()
        {
            return "InputMsg: " +
            "\nthrottle: " + throttle.ToString() +
            "\nbrake: " + brake.ToString() +
            "\nsteering_angle: " + steering_angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
