//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UgvAssignment
{
    [Serializable]
    public class OutputMsg : Message
    {
        public const string k_RosMessageName = "ugv_assignment_msgs/Output";
        public override string RosMessageName => k_RosMessageName;

        public string state;
        public double linear_velocity;
        public double angular_velocity;
        public double front_left_steering_angle;
        public double front_right_steering_angle;

        public OutputMsg()
        {
            this.state = "";
            this.linear_velocity = 0.0;
            this.angular_velocity = 0.0;
            this.front_left_steering_angle = 0.0;
            this.front_right_steering_angle = 0.0;
        }

        public OutputMsg(string state, double linear_velocity, double angular_velocity, double front_left_steering_angle, double front_right_steering_angle)
        {
            this.state = state;
            this.linear_velocity = linear_velocity;
            this.angular_velocity = angular_velocity;
            this.front_left_steering_angle = front_left_steering_angle;
            this.front_right_steering_angle = front_right_steering_angle;
        }

        public static OutputMsg Deserialize(MessageDeserializer deserializer) => new OutputMsg(deserializer);

        private OutputMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
            deserializer.Read(out this.linear_velocity);
            deserializer.Read(out this.angular_velocity);
            deserializer.Read(out this.front_left_steering_angle);
            deserializer.Read(out this.front_right_steering_angle);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.linear_velocity);
            serializer.Write(this.angular_velocity);
            serializer.Write(this.front_left_steering_angle);
            serializer.Write(this.front_right_steering_angle);
        }

        public override string ToString()
        {
            return "OutputMsg: " +
            "\nstate: " + state.ToString() +
            "\nlinear_velocity: " + linear_velocity.ToString() +
            "\nangular_velocity: " + angular_velocity.ToString() +
            "\nfront_left_steering_angle: " + front_left_steering_angle.ToString() +
            "\nfront_right_steering_angle: " + front_right_steering_angle.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
